import Link from 'next/link';
import { ArrowLeft, RefreshCw, AlertCircle } from 'lucide-react';

export const metadata = {
  title: 'Refund Policy | KhataX',
  description: 'Understand the KhataX cancellation and refund policies.',
};

export default function RefundPolicyPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white selection:bg-[#00ea77]/30 selection:text-white font-sans flex flex-col">
      <header className="p-6 border-b border-white/10 flex items-center justify-between z-10 relative bg-[#0a0a0a]">
        <Link href="/" className="flex items-center gap-2 hover:opacity-80 transition-opacity">
          <div className="w-8 h-8 rounded bg-[#00ea77] flex items-center justify-center">
             <div className="w-2.5 h-2.5 bg-black rounded-sm"></div>
          </div>
          <span className="font-bold text-xl tracking-tight">KhataX</span>
        </Link>
        <Link href="/" className="text-sm font-semibold text-slate-400 hover:text-white flex items-center gap-2 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
      </header>
      
      <main className="flex-1 flex justify-center p-12 lg:p-24 relative overflow-hidden">
        <div className="max-w-3xl w-full relative z-10">
          <div className="mb-12">
            <h1 className="text-4xl md:text-5xl font-extrabold mb-6">Refund & Cancellation</h1>
            <p className="text-lg text-slate-400">Clear, mathematically precise guidelines on subscription cancellations.</p>
          </div>
          
          <div className="bg-[#111] border border-white/10 rounded-3xl p-8 md:p-12 space-y-8 text-slate-300 leading-relaxed">
            
            <div className="flex gap-4">
              <RefreshCw className="w-6 h-6 text-[#00ea77] shrink-0 mt-1" />
              <div>
                <h3 className="text-xl font-bold text-white mb-2">1. 14-Day Vault Guarantee</h3>
                <p>KhataX provides an unconditional 14-day refund window for all new **Yearly** configurations. If the UI framework or native capabilities do not meet your exact engineering specifications, cancel within 14 days for a completely mathematically zeroed refund matrix.</p>
              </div>
            </div>

            <div className="flex gap-4">
              <AlertCircle className="w-6 h-6 text-yellow-500 shrink-0 mt-1" />
              <div>
                <h3 className="text-xl font-bold text-white mb-2">2. Monthly Terminals</h3>
                <p>Due to the massive upfront server loads generated by our native AI Insights compute engines, all monthly subscriptions (e.g. ₹299/mo) are strictly non-refundable once initiated. You may cancel renewal at any time natively in your dashboard array.</p>
              </div>
            </div>

            <div className="pt-8 border-t border-white/10 mt-8">
              <p className="text-white font-bold mb-2">To trigger a Cancellation Pipeline:</p>
              <ul className="list-disc pl-5 space-y-2 text-sm text-slate-400">
                 <li>Navigate to Settings &gt; Billing Configuration array.</li>
                 <li>Select `Halt Subscription`.</li>
                 <li>If you fall within the 14-day yearly loop, the payment gateway natively refunds to your origination account within 5-7 business nodes.</li>
              </ul>
            </div>
            
          </div>
        </div>
      </main>
    </div>
  );
}
